trigger:
- feature/bmeza

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: DEVOPS_TEST_DEV

# resources:
#   containers:
#   - container: mtc-api-logtag-container
#     image: ryandf1998/mtc-api-logtag-container:latest

stages:
  - stage: Build
    displayName: Build stage
    jobs:

    - job: Build
      displayName: 'Build and Push Docker Image'
      steps:

      - task: AzurePowerShell@5
        inputs:
          azureSubscription: DEVOPS_TEST_SERVICE_CONNECTION
          ScriptType: InlineScript
          azurePowerShellVersion: Latest
          Inline: |
            Set-Content -Path "src/main/resources/application.properties" -Value (Get-Content -Path "src/main/resources/application.properties" | ForEach-Object { $_ -replace '\$\{DEVOPS_TEST_DEV_URI_DEV\}', '$(DEVOPS_TEST_DEV_URI_DEV)' -replace '\$\{DEVOPS_TEST_DEV_JWT_DEV\}', '$(DEVOPS_TEST_DEV_JWT_DEV)' })
            Get-Content -Path src/main/resources/application.properties -TotalCount 5

      - task: Maven@3
        inputs:
          mavenPOMFile: 'pom.xml'
          testResultsFiles: '**/target/jacoco.exec'
          codeCoverageToolOption: 'JaCoCo'
          publishJUnitResults: true
          mavenVersionOption: '3.8.5'

      # - task: Docker@2
      #   inputs:
      #     containerRegistry: 'mtc-api-docker-hub'
      #     repository: 'ryandf1998/mtc-api-logtag-container'
      #     command: 'buildAndPush'
      #     Dockerfile: '**/Dockerfile'
      #     tags: latest

  # - stage: test
  #   displayName: Test
  #   jobs:

  #   - job: my_custom_container_job
  #     displayName: 'Build and Push Docker Image'
  #     container:
  #         image: ryandf1998/mtc-api-logtag-container:latest
  #     steps:
  #         - checkout: self
  #         - script: |
  #             echo "Hello from custom container"
  #             df

