trigger:
- feature/bmeza

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: DEVOPS_TEST_DEV

# resources:
#   containers:
#   - container: mtc-api-logtag-container
#     image: ryandf1998/mtc-api-logtag-container:latest

stages:
  - stage: Build
    displayName: Build stage
    jobs:

    - job: Build
      displayName: 'Build and Push Docker Image'
      steps:

      - task: AzurePowerShell@5
        inputs:
          azureSubscription: DEVOPS_TEST_SERVICE_CONNECTION
          ScriptType: InlineScript
          azurePowerShellVersion: Latest
          Inline: |
            Set-Content -Path "src/main/resources/application.properties" -Value (Get-Content -Path "src/main/resources/application.properties" | ForEach-Object { $_ -replace '\$\{DEVOPS_TEST_DEV_URI_DEV\}', '$(DEVOPS_TEST_DEV_URI_DEV)' -replace '\$\{DEVOPS_TEST_DEV_JWT_DEV\}', '$(DEVOPS_TEST_DEV_JWT_DEV)' })
            Get-Content -Path src/main/resources/application.properties -TotalCount 5

      - task: Bash@3
        inputs:
          targetType: inline
          script: |
            docker build -t devops-unit-test-img -f './docker-test/Dockerfile' .
            docker run -d --name devops-unit-test-cont devops-unit-test-img
            docker cp devops-unit-test-cont:/app/target/ surefire-reports/
            docker cp devops-unit-test-cont:/app/target/site/jacoco/jacoco.xml jacoco/
            docker rm -f devops-unit-test-cont
            ls -lrt surefire-reports/
      
      # - task: PublishTestResults@2
      #   inputs:  
      #     testResultsFormat: 'JUnit'
      #     testResultsFiles: 'surefire-reports/*.xml'

      # - task: PublishCodeCoverageResults@2
      #   inputs:
      #     summaryFileLocation: 'jacoco/jacoco.xml'


      # - task: Docker@2
      #   inputs:
      #     containerRegistry: 'mtc-api-docker-hub'
      #     repository: 'ryandf1998/mtc-api-logtag-container'
      #     command: 'buildAndPush'
      #     Dockerfile: '**/Dockerfile'
      #     tags: latest

  # - stage: test
  #   displayName: Test
  #   jobs:

  #   - job: my_custom_container_job
  #     displayName: 'Build and Push Docker Image'
  #     container:
  #         image: ryandf1998/mtc-api-logtag-container:latest
  #     steps:
  #         - checkout: self
  #         - script: |
  #             echo "Hello from custom container"
  #             df

