trigger:
- feature/bmeza

pool:
  vmImage: 'ubuntu-latest'

variables: 
  - group: DEVOPS_TEST_DEV

jobs:
- job: Build
  displayName: 'Build and Push Docker Image'
  steps:

  - task: AzurePowerShell@5
    inputs:
      azureSubscription: DEVOPS_TEST_SERVICE_CONNECTION
      ScriptType: InlineScript
      azurePowerShellVersion: Latest
      Inline: |
        Set-Content -Path "src/main/resources/application.properties" -Value (Get-Content -Path "src/main/resources/application.properties" | ForEach-Object { $_ -replace '\$\{DEVOPS_TEST_DEV_URI_DEV\}', '$(DEVOPS_TEST_DEV_URI_DEV)' -replace '\$\{DEVOPS_TEST_DEV_JWT_DEV\}', '$(DEVOPS_TEST_DEV_JWT_DEV)' })
        Get-Content -Path src/main/resources/application.properties -TotalCount 5

  - task: Docker@2
    inputs:
      containerRegistry: 'mtc-api-docker-hub'
      repository: 'ryandf1998/mtc-api-logtag-container'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: latest

  - task: Docker@2
    displayName: 'Run unit tests'
    inputs:
      containerRegistry: 'mtc-api-docker-hub'
      command: 'start'
      container: 'ryandf1998/mtc-api-logtag-container:latest'

# - job: Deploy
#   displayName: 'Deploy to Azure App Service'
#   dependsOn: Build
#   steps:
#     - task: AzureWebAppContainer@1
#       inputs:
#         azureSubscription: DEVOPS_TEST_SERVICE_CONNECTION
#         appName: proddevopstappserv
#         containers: ryandf1998/mtc-api-logtag-container:latest
#         #containerCommand: docker login -u ryandf1998 -p $(DEVOPS_TEST_DR_PASS_DEV)
